version: '3'

services:
  api:
    build: .
    restart: always
    ports:
      - '1323:1323'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
      JWT_SECRET: secret

  db:
    image: postgres:14.5-alpine
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres